### PR TITLE
Update to react/http v1

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Comment by mbonneau** [comment]
@WyriHaximus I have been taking a look at this PR for a bit - I cannot get the Autobahn tests to run (trying the client tests right now). Were you able to get the tests running?

**Comment by WyriHaximus** [comment]
@mbonneau Errr locally maybe as they require some Pythong deps, will have a look at this again this weekend. Probably also include a migration to GA since Travis is shutting down. 

Also this is one of several steps in this PR, as I want to move the client part to `Pawl`.

**Comment by mbonneau** [comment]
@WyriHaximus I didn't see that this was a draft PR.

I did take a look at the client side problem I was having and it looks like we need to add
```php
$clientObserver->onCompleted();
```
inside the ```$request->on('close'...)``` event handler in `Client.php`. I am guessing there were some changes to the underlying libraries where `end` is not called every time anymore. After reading, it looks like the `close` handler may be the more appropriate place anyway.

**Comment by WyriHaximus** [comment]
@mbonneau Sorry I completely forgot about this PR :scream: . But glad to see it's merged in now.

**Pull request merged**
